services:
  rabbitmq:
    container_name: 'rabbitmq-football-match-calendar-sync-dev'
    image: 'rabbitmq:4.3.6-management-alpine'
    environment:
      - 'RABBITMQ_DEFAULT_USER=admin'
      - 'RABBITMQ_DEFAULT_PASS=secret'
    ports:
      - '5672:5672'
      - '15672:15672'